import { React, HTML, CSS, Javascript, PHP, Java, Laravel, TailwindCSS, Nextjs, Bootstrap, Redux, Hono, MySQL, Prisma, VsCode, Figma, NodeJs, Bun, PostgreSQL, MongoDB, Git } from '../assets/LangSVG'

export const SVG_CALL = {
    "HTML": <HTML />,
    "React.js": <React />,
    "CSS": <CSS />,
    "Javascript": <Javascript />,
    "PHP": <PHP />,
    "Java": <Java />,
    "Laravel": <Laravel />,
    "Tailwind CSS": <TailwindCSS />,
    "Next.js": <Nextjs />,
    "Bootstrap": <Bootstrap />,
    "Redux.js": <Redux />,
    "Hono": <Hono />,
    "MySQL": <MySQL />,
    "PostgreSQL": <PostgreSQL />,
    "MongoDB": <MongoDB />,
    "Prisma": <Prisma />,
    "VsCode": <VsCode />,
    "Figma": <Figma />,
    "Node.js": <NodeJs />,
    "Bun": <Bun />,
    "Git": <Git />,
  }